# -*- coding: utf-8 -*-
"""0218Selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpTX7Z5hPgxnGgrY4luNx6dmNgdVxwT4

Decision-Making / Selection
"""

wage = 23
gross = 0.0
hours = 45
hour_limit = 40

if hours<= hour_limit:
  gross = wage * hours
else:
  gross = hour_limit * wage
  gross += (hours - hour_limit) * wage * 1.5
print(gross)

"""Customer Analytics"""

import pandas as pd
import scipy.stats
xl = pd.ExcelFile("/content/TableauSalesData (1).xlsx")
SalesData = xl.parse("Orders")

#Show us name and date from top to bottom, one drops duplicates, one does not
CustomerOrderData = SalesData[['Customer Name', "Order Date"]].sort_values(by="Order Date", ascending = False)
RecentCustomers = CustomerOrderData.drop_duplicates()
print(RecentCustomers.head(10))
print(CustomerOrderData.head(10))

#Shows us customer orders while dropping the duplicates
CustomerOrders = SalesData[["Customer Name", "Order Date"]].drop_duplicates()
FrequentItems = CustomerOrders["Customer Name"].value_counts()
print(FrequentItems.head(10))

#Tells us how many unique customers there are without duplicates and percentage 
UniqueCustomer = SalesData["Customer Name"].drop_duplicates()
CustomerCount = UniqueCustomer.shape[0]
print(CustomerCount)
Top3Percent = int(CustomerCount*0.03)
MostRecent = SalesData[["Customer Name", "Order Date"]].sort_values(by="Order Date", ascending = False)
print(Top3Percent)

#Shows how much money spent by each customer
CustMonetaryValue = SalesData[["Customer Name", "Sales"]].groupby(by="Customer Name").sum().sort_values(by="Sales", ascending =False).round()
print(CustMonetaryValue)

UserInput = 1
if UserInput == "1":
  print("You will now be directed to the product page")
elif UserInput == "2":
  print("You will now be directed to the customer page")
elif UserInput == "3":
  print("You will now be directed to the registration page")
else:
  print("Please select 1, 2, or 3")

What2Eat = "Burger"
if What2Eat == "Burger":
  print("I will eat a Burger!")
elif What2Eat == "Salad":
  print("I will eat a Salad!")
elif What2Eat == "Sandwhich":
  print("I will eat a Sandwhich!")
else:
  print("I need to lose weight, no food for me.")